# Generated by Django 3.0.3 on 2020-02-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='projects_photos/')),
                ('resume', models.FileField(upload_to='resume/')),
            ],
        ),
    ]
